# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertoken',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
