# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170301_0328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChannels',
            new_name='UserChannel',
        ),
    ]
