# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170218_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registertoken',
            options={'ordering': ('use', '-created_at')},
        ),
        migrations.AddField(
            model_name='registertoken',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registertoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
