# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170219_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddon',
            name='valid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddon',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useraddon',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
