# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170222_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddon',
            old_name='message_channel',
            new_name='channel',
        ),
        migrations.RemoveField(
            model_name='useraddon',
            name='online',
        ),
    ]
